#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

MYDLPCONF="/etc/mydlp/mydlp.conf"
MYDLPDUMPDIR="/var/lib/mydlp/revision"
MYSQLC=/usr/bin/mysql
MYSQLDUMPC=/usr/bin/mysqldump
MYSQLOPTS="-N"
MYSQLDUMPOPTS="--no-create-db --no-create-info --skip-comments --skip-add-locks"

if [ -n "$1" ]; then
	MYDLPCONF=$1
fi

MYSQLHOST=$(grep -e "^mysql_host" $MYDLPCONF|cut -f 2)
MYSQLPORT=$(grep -e "^mysql_port" $MYDLPCONF|cut -f 2)
MYSQLUSER=$(grep -e "^mysql_user" $MYDLPCONF|cut -f 2)
MYSQLPW=$(grep -e "^mysql_password" $MYDLPCONF|cut -f 2)
MYSQLDB=$(grep -e "^mysql_database" $MYDLPCONF|cut -f 2)

MYSQLARGS=""

if [ "$MYSQLHOST" != "localhost" ]; then
	MYSQLARGS="$MYSQLARGS -h $MYSQLHOST"
	if [ "$MYSQLPORT" != "3306" ]; then
		MYSQLARGS="$MYSQLARGS -P $MYSQLPORT"
	fi
fi

MYSQLARGS="$MYSQLARGS -u $MYSQLUSER"

if [ "$MYSQLPW" != '""' ]; then
	MYSQLARGS="$MYSQLARGS -p$MYSQLPW"
fi

MYSQLARGS="$MYSQLARGS $MYSQLDB"
MYSQL="$MYSQLC $MYSQLOPTS $MYSQLARGS"
MYSQLDUMP="$MYSQLDUMPC $MYSQLDUMPOPTS $MYSQLARGS"

REVISION_TABLE="Revision"

function queryTables() {
	echo "SHOW TABLES;"|$MYSQL
}

function getTableNames() {
	queryTables|while read line
	do
		if [ "$line" != $REVISION_TABLE ]; then
			echo $line
		fi
	done
}

function dumpCurrent() {
	local TABLES=$(getTableNames)
	for t in $TABLES
	do
		echo "TRUNCATE $t;"
	done

	$MYSQLDUMP $TABLES
}

TMPFILE=$(mktemp)

DUMPFILENAME=""

generateFilename() {
	local HASH=$(md5sum $TMPFILE|cut -d' ' -f1)
	DUMPFILENAME=$MYDLPDUMPDIR/$HASH.gz
}

writeToFile() {
	if [ -e "$DUMPFILENAME" ]; then
		true
	else
		cat $TMPFILE | gzip -c > $DUMPFILENAME
	fi
}

function addNewRevision() {
	local LAST_PATH=$(echo "SELECT dumpPath FROM $REVISION_TABLE ORDER BY id DESC LIMIT 1"|$MYSQL)
	if [ -n "$LAST_PATH" -a "$LAST_PATH" == "$DUMPFILENAME" ]; then
		true
	else
		echo "INSERT INTO $REVISION_TABLE (id, date, isInstalled, dumpPath) VALUES ('',now(), false, '$DUMPFILENAME')"|$MYSQL
	fi
}


dumpCurrent > $TMPFILE && generateFilename && writeToFile && addNewRevision

rm -f $TMPFILE

