#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

MYDLPCONF="/etc/mydlp/mydlp.conf"
MYDLPDUMPDIR="/var/lib/mydlp/revision"
MYSQLC=/usr/bin/mysql
MYSQLOPTS="-N"

if [ -n "$1" ]; then
	MYDLPCONF=$1
fi

MYSQLHOST=$(grep -e "^mysql_host" $MYDLPCONF|cut -f 2)
MYSQLPORT=$(grep -e "^mysql_port" $MYDLPCONF|cut -f 2)
MYSQLUSER=$(grep -e "^mysql_user" $MYDLPCONF|cut -f 2)
MYSQLPW=$(grep -e "^mysql_password" $MYDLPCONF|cut -f 2)
MYSQLDB=$(grep -e "^mysql_database" $MYDLPCONF|cut -f 2)

MYSQLARGS=""

if [ "$MYSQLHOST" != "localhost" ]; then
	MYSQLARGS="$MYSQLARGS -h $MYSQLHOST"
	if [ "$MYSQLPORT" != "3306" ]; then
		MYSQLARGS="$MYSQLARGS -P $MYSQLPORT"
	fi
fi

MYSQLARGS="$MYSQLARGS -u $MYSQLUSER"

if [ "$MYSQLPW" != '""' ]; then
	MYSQLARGS="$MYSQLARGS -p$MYSQLPW"
fi

MYSQLARGS="$MYSQLARGS $MYSQLDB"
MYSQL="$MYSQLC $MYSQLOPTS $MYSQLARGS"

REVISION_TABLE="Revision"

echo "SELECT date, name, dumpPath FROM $REVISION_TABLE ORDER BY id DESC"|$MYSQL

