ALTER TABLE ADDomainItem DROP KEY distinguishedName;
ALTER TABLE ADDomain MODIFY COLUMN domainName VARCHAR(190) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE ADDomainItem MODIFY COLUMN distinguishedName VARCHAR(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE AuthUser MODIFY COLUMN username VARCHAR(127) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE Config MODIFY COLUMN configKey VARCHAR(127) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE ADDomainItem ADD COLUMN distinguishedNameHash INT(11) NOT NULL COMMENT '', ADD CONSTRAINT distinguishedNameHash UNIQUE KEY(distinguishedNameHash);
