ALTER TABLE IncidentLogFile ADD COLUMN blueprint_id INT(11) NULL DEFAULT NULL COMMENT '', ADD INDEX FKDAB6258ED0CBCEBB (blueprint_id);
ALTER TABLE IncidentLogFileContent ADD COLUMN md5Hash VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '', ADD INDEX hashIndex (md5Hash(191));
CREATE TABLE IncidentLogFileBlueprint (
    id INT(11) AUTO_INCREMENT NOT NULL,
    md5Hash VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    mimeType VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    size BIGINT(20) NULL DEFAULT NULL,
    INDEX hashIndex (md5Hash(191)),
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
ALTER TABLE IncidentLogFile ADD CONSTRAINT FKDAB6258ED0CBCEBB FOREIGN KEY FKDAB6258ED0CBCEBB (blueprint_id) REFERENCES IncidentLogFileBlueprint (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
