CREATE TABLE Domain (
    destinationString VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE FileSystemDirectory (
    destinationString VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
ALTER TABLE Domain ADD CONSTRAINT FK7A58C0E41955299D FOREIGN KEY (id) REFERENCES Item (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE FileSystemDirectory ADD CONSTRAINT FK678733C21955299D FOREIGN KEY (id) REFERENCES Item (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
