CREATE TABLE EndpointItem (
    id INT(11) NOT NULL,
    endpoint_id INT(11) NOT NULL,
    INDEX FKD7128E68D69B5F89 (endpoint_id),
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE Hostname (
    hostname VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
ALTER TABLE EndpointItem ADD CONSTRAINT FKD7128E68D69B5F89 FOREIGN KEY (endpoint_id) REFERENCES Endpoint (id) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FKD7128E681955299D FOREIGN KEY (id) REFERENCES Item (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE Hostname ADD CONSTRAINT FKF1FBC0531955299D FOREIGN KEY (id) REFERENCES Item (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
