ALTER TABLE MatchingDetail DROP INDEX incidentLogIndex, DROP COLUMN incidentLogId, DROP COLUMN matcherId;
ALTER TABLE MatchingDetail ADD COLUMN matcherFunc VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '', ADD COLUMN incidentLog_id INT(11) NOT NULL COMMENT '', ADD INDEX FKD364CACE5A33480B (incidentLog_id);
ALTER TABLE MatchingDetail ADD CONSTRAINT FKD364CACE5A33480B FOREIGN KEY FKD364CACE5A33480B (incidentLog_id) REFERENCES IncidentLog (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
