CREATE TABLE DailySchedule (
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE RemoteStorage (
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE RemoteStorageCIFS (
    password VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    path VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    username VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    windowsShare VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE RemoteStorageDFS (
    password VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    path VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    username VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    windowsShare VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE RemoteStorageFTPFS (
    address VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    password VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    path VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    username VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE RemoteStorageNFS (
    address VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    path VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE RemoteStorageSSHFS (
    address VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    password VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    path VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    port INT(11) NOT NULL,
    username VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE RuleSchedule (
    id INT(11) AUTO_INCREMENT NOT NULL,
    rule_id INT(11) NOT NULL,
    schedule_id INT(11) NOT NULL,
    scheduleIntervals_id INT(11) NOT NULL,
    INDEX FKEBA925D3936C2849 (schedule_id),
    INDEX FKEBA925D375A7E1A9 (rule_id),
    INDEX FKEBA925D38732C12B (scheduleIntervals_id),
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE Schedule (
    id INT(11) AUTO_INCREMENT NOT NULL,
    hour INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE ScheduleDayInterval (
    id INT(11) AUTO_INCREMENT NOT NULL,
    hour00 TINYINT(1) NULL DEFAULT NULL,
    hour01 TINYINT(1) NULL DEFAULT NULL,
    hour02 TINYINT(1) NULL DEFAULT NULL,
    hour03 TINYINT(1) NULL DEFAULT NULL,
    hour04 TINYINT(1) NULL DEFAULT NULL,
    hour05 TINYINT(1) NULL DEFAULT NULL,
    hour06 TINYINT(1) NULL DEFAULT NULL,
    hour07 TINYINT(1) NULL DEFAULT NULL,
    hour08 TINYINT(1) NULL DEFAULT NULL,
    hour09 TINYINT(1) NULL DEFAULT NULL,
    hour10 TINYINT(1) NULL DEFAULT NULL,
    hour11 TINYINT(1) NULL DEFAULT NULL,
    hour12 TINYINT(1) NULL DEFAULT NULL,
    hour13 TINYINT(1) NULL DEFAULT NULL,
    hour14 TINYINT(1) NULL DEFAULT NULL,
    hour15 TINYINT(1) NULL DEFAULT NULL,
    hour16 TINYINT(1) NULL DEFAULT NULL,
    hour17 TINYINT(1) NULL DEFAULT NULL,
    hour18 TINYINT(1) NULL DEFAULT NULL,
    hour19 TINYINT(1) NULL DEFAULT NULL,
    hour20 TINYINT(1) NULL DEFAULT NULL,
    hour21 TINYINT(1) NULL DEFAULT NULL,
    hour22 TINYINT(1) NULL DEFAULT NULL,
    hour23 TINYINT(1) NULL DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE ScheduleIntervals (
    id INT(11) AUTO_INCREMENT NOT NULL,
    fri_id INT(11) NULL DEFAULT NULL,
    mon_id INT(11) NULL DEFAULT NULL,
    sat_id INT(11) NULL DEFAULT NULL,
    sun_id INT(11) NULL DEFAULT NULL,
    thu_id INT(11) NULL DEFAULT NULL,
    tue_id INT(11) NULL DEFAULT NULL,
    wed_id INT(11) NULL DEFAULT NULL,
    INDEX FK76627B57E64E2349 (mon_id),
    INDEX FK76627B57EFC8A82F (sat_id),
    INDEX FK76627B57F2908551 (tue_id),
    INDEX FK76627B57F1E099B4 (thu_id),
    INDEX FK76627B57F0DFC409 (sun_id),
    INDEX FK76627B57F6CD22BF (wed_id),
    INDEX FK76627B57DA843798 (fri_id),
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE WebServer (
    address VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    digDepth INT(11) NOT NULL,
    port INT(11) NOT NULL,
    proto VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    startPath VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE WeeklySchedule (
    fri TINYINT(1) NULL DEFAULT NULL,
    mon TINYINT(1) NULL DEFAULT NULL,
    sat TINYINT(1) NULL DEFAULT NULL,
    sun TINYINT(1) NULL DEFAULT NULL,
    thu TINYINT(1) NULL DEFAULT NULL,
    tue TINYINT(1) NULL DEFAULT NULL,
    wed TINYINT(1) NULL DEFAULT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
ALTER TABLE DailySchedule ADD CONSTRAINT FK547FDBB088EDF1A1 FOREIGN KEY (id) REFERENCES Schedule (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE RemoteStorage ADD CONSTRAINT FKDE0857351955299D FOREIGN KEY (id) REFERENCES Item (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE RemoteStorageCIFS ADD CONSTRAINT FK670F446848A2BFE1 FOREIGN KEY (id) REFERENCES RemoteStorage (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE RemoteStorageDFS ADD CONSTRAINT FK2C9D68BC48A2BFE1 FOREIGN KEY (id) REFERENCES RemoteStorage (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE RemoteStorageFTPFS ADD CONSTRAINT FK7B08B37A48A2BFE1 FOREIGN KEY (id) REFERENCES RemoteStorage (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE RemoteStorageNFS ADD CONSTRAINT FK2C9D8E4648A2BFE1 FOREIGN KEY (id) REFERENCES RemoteStorage (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE RemoteStorageSSHFS ADD CONSTRAINT FK7BBF52A048A2BFE1 FOREIGN KEY (id) REFERENCES RemoteStorage (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE RuleSchedule ADD CONSTRAINT FKEBA925D38732C12B FOREIGN KEY (scheduleIntervals_id) REFERENCES ScheduleIntervals (id) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FKEBA925D375A7E1A9 FOREIGN KEY (rule_id) REFERENCES Rule (id) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FKEBA925D3936C2849 FOREIGN KEY (schedule_id) REFERENCES Schedule (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE ScheduleIntervals ADD CONSTRAINT FK76627B57E64E2349 FOREIGN KEY (mon_id) REFERENCES ScheduleDayInterval (id) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FK76627B57F1E099B4 FOREIGN KEY (thu_id) REFERENCES ScheduleDayInterval (id) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FK76627B57F6CD22BF FOREIGN KEY (wed_id) REFERENCES ScheduleDayInterval (id) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FK76627B57F2908551 FOREIGN KEY (tue_id) REFERENCES ScheduleDayInterval (id) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FK76627B57F0DFC409 FOREIGN KEY (sun_id) REFERENCES ScheduleDayInterval (id) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FK76627B57EFC8A82F FOREIGN KEY (sat_id) REFERENCES ScheduleDayInterval (id) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FK76627B57DA843798 FOREIGN KEY (fri_id) REFERENCES ScheduleDayInterval (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE WebServer ADD CONSTRAINT FK32A237971955299D FOREIGN KEY (id) REFERENCES Item (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE WeeklySchedule ADD CONSTRAINT FK1E53325888EDF1A1 FOREIGN KEY (id) REFERENCES Schedule (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
