ALTER TABLE InventoryItem ADD COLUMN group_id INT(11) NULL DEFAULT NULL COMMENT '', ADD INDEX FKD4AE2A6FC7D9C00D (group_id);
CREATE TABLE InventoryGroup (
    itemType VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE RuleItemGroup (
    id INT(11) AUTO_INCREMENT NOT NULL,
    group_id INT(11) NOT NULL,
    rule_id INT(11) NOT NULL,
    INDEX FK121D537075A7E1A9 (rule_id),
    INDEX FK121D5370C7D9C00D (group_id),
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
CREATE TABLE StringArgument (
    argument VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    id INT(11) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB COLLATE=utf8mb4_general_ci;
ALTER TABLE InventoryGroup ADD CONSTRAINT FKC0FA32A33F451ED9 FOREIGN KEY (id) REFERENCES InventoryBase (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE RuleItemGroup ADD CONSTRAINT FK121D5370C7D9C00D FOREIGN KEY (group_id) REFERENCES InventoryGroup (id) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FK121D537075A7E1A9 FOREIGN KEY (rule_id) REFERENCES Rule (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE StringArgument ADD CONSTRAINT FK11614E0E53C6BDC7 FOREIGN KEY (id) REFERENCES Argument (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE InventoryItem ADD CONSTRAINT FKD4AE2A6FC7D9C00D FOREIGN KEY FKD4AE2A6FC7D9C00D (group_id) REFERENCES InventoryGroup (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
