ALTER TABLE SourceDomainName DROP FOREIGN KEY FK6DBC240A1955299D;
DROP TABLE SourceDomainName;
ALTER TABLE RuleItem ADD COLUMN ruleColumn VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '';
