ALTER TABLE MatchingDetail DROP FOREIGN KEY FKD364CACE5A33480B;
ALTER TABLE MatchingDetail DROP INDEX FKD364CACE5A33480B, DROP COLUMN incidentLog_id;
ALTER TABLE MatchingDetail ADD COLUMN incidentLogFile_id INT(11) NOT NULL COMMENT '', ADD INDEX FKD364CACE72F76A2B (incidentLogFile_id);
ALTER TABLE MatchingDetail ADD CONSTRAINT FKD364CACE72F76A2B FOREIGN KEY FKD364CACE72F76A2B (incidentLogFile_id) REFERENCES IncidentLogFile (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
