#!/bin/bash
###--------------------------------------------------------------------------
###
###    Copyright (C) 2010 Huseyin Kerem Cevahir <kerem@medra.com.tr>
###
###--------------------------------------------------------------------------
###    This file is part of MyDLP.
###
###    MyDLP is free software: you can redistribute it and/or modify
###    it under the terms of the GNU General Public License as published by
###    the Free Software Foundation, either version 3 of the License, or
###    (at your option) any later version.
###
###    MyDLP is distributed in the hope that it will be useful,
###    but WITHOUT ANY WARRANTY; without even the implied warranty of
###    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
###    GNU General Public License for more details.
###
###    You should have received a copy of the GNU General Public License
###    along with MyDLP.  If not, see <http://www.gnu.org/licenses/>.
###--------------------------------------------------------------------------

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

MYDLP_STORE=/var/lib/mydlp/mnesia

echo -n "Do you really want to reset MyDLP runtime database? (y/N): "

read line

if [ -n "$line" -a "$line" == "y" ]; then
	service mydlp status && service mydlp stop && sleep 3
	rm -f $MYDLP_STORE/*
	echo "Stopped MyDLP and cleaned MyDLP runtime database."
	echo "You should start MyDLP Service again."
else
	echo "Nothing is changed."
	exit 1
fi

exit 0
